//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirIQ.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AirIQ.Resources.Strings.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Departure Airport.
        /// </summary>
        internal static string SearchDepartureAirport {
            get {
                return ResourceManager.GetString("SearchDepartureAirport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Destination Airport.
        /// </summary>
        internal static string SearchDestinationAirport {
            get {
                return ResourceManager.GetString("SearchDestinationAirport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Date.
        /// </summary>
        internal static string TravelDate {
            get {
                return ResourceManager.GetString("TravelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pax Size.
        /// </summary>
        internal static string PaxSize {
            get {
                return ResourceManager.GetString("PaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Flights.
        /// </summary>
        internal static string SearchFlights {
            get {
                return ResourceManager.GetString("SearchFlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flights.
        /// </summary>
        internal static string Flights {
            get {
                return ResourceManager.GetString("Flights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotels.
        /// </summary>
        internal static string Hotels {
            get {
                return ResourceManager.GetString("Hotels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to AIR iQ.
        /// </summary>
        internal static string WelcomeToAIRiQ {
            get {
                return ResourceManager.GetString("WelcomeToAIRiQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to continue.
        /// </summary>
        internal static string SignInToContinue {
            get {
                return ResourceManager.GetString("SignInToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        internal static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an Account.
        /// </summary>
        internal static string CreateAnAccount {
            get {
                return ResourceManager.GetString("CreateAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2025 AIR iQ Groups &amp; Series.
        /// </summary>
        internal static string AIRIQGroupsSeries {
            get {
                return ResourceManager.GetString("AIRIQGroupsSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Required.
        /// </summary>
        internal static string InformationRequired {
            get {
                return ResourceManager.GetString("InformationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired, please enter your password to continue..
        /// </summary>
        internal static string SessionExpired {
            get {
                return ResourceManager.GetString("SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Booking.
        /// </summary>
        internal static string ConfirmBooking {
            get {
                return ResourceManager.GetString("ConfirmBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username.
        /// </summary>
        internal static string EnterUsername {
            get {
                return ResourceManager.GetString("EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGENT LOGIN.
        /// </summary>
        internal static string AgentLogin {
            get {
                return ResourceManager.GetString("AgentLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t have an account? .
        /// </summary>
        internal static string DontHaveAccount {
            get {
                return ResourceManager.GetString("DontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms & Conditions.
        /// </summary>
        internal static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to your account.
        /// </summary>
        internal static string LoginToYourAccount {
            get {
                return ResourceManager.GetString("LoginToYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by.
        /// </summary>
        internal static string PoweredBy {
            get {
                return ResourceManager.GetString("PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDAANHOTELS.COM.
        /// </summary>
        internal static string UdaanHotels {
            get {
                return ResourceManager.GetString("UdaanHotels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book your flight with.
        /// </summary>
        internal static string BookYourFlightWith {
            get {
                return ResourceManager.GetString("BookYourFlightWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air.
        /// </summary>
        internal static string Air {
            get {
                return ResourceManager.GetString("Air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ.
        /// </summary>
        internal static string IQ {
            get {
                return ResourceManager.GetString("IQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure.
        /// </summary>
        internal static string Departure {
            get {
                return ResourceManager.GetString("Departure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travelers.
        /// </summary>
        internal static string Travelers {
            get {
                return ResourceManager.GetString("Travelers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Ticket.
        /// </summary>
        internal static string BookTicket {
            get {
                return ResourceManager.GetString("BookTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Code.
        /// </summary>
        internal static string TourCode {
            get {
                return ResourceManager.GetString("TourCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details Provided.
        /// </summary>
        internal static string DetailsProvided {
            get {
                return ResourceManager.GetString("DetailsProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult.
        /// </summary>
        internal static string Adult {
            get {
                return ResourceManager.GetString("Adult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR IQ.
        /// </summary>
        internal static string AIRIQ {
            get {
                return ResourceManager.GetString("AIRIQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARKETPLACE.
        /// </summary>
        internal static string MARKETPLACE {
            get {
                return ResourceManager.GetString("MARKETPLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traveller Details.
        /// </summary>
        internal static string TravellerDetails {
            get {
                return ResourceManager.GetString("TravellerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Infant.
        /// </summary>
        internal static string AddInfant {
            get {
                return ResourceManager.GetString("AddInfant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have READ and AGREE to the.
        /// </summary>
        internal static string READAndAGREE {
            get {
                return ResourceManager.GetString("READAndAGREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERSONAL INFORMATION.
        /// </summary>
        internal static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT INFORMATION.
        /// </summary>
        internal static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUSINESS INFORMATION.
        /// </summary>
        internal static string BusinessInformation {
            get {
                return ResourceManager.GetString("BusinessInformation", resourceCulture);
            }
        }
    }
}
